url: https://github.com/rancher/ob-team-charts.git
subdirectory: charts/rancher-monitoring/69.8.2-rancher.30
commit: dad599bfd0560ee6b5ca0d4408180964987c3978
version: 107.2.3-rc.1
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/ob-team-charts.git
      subdirectory: charts/rancher-monitoring-crd/69.8.2-rancher.30
      commit: dad599bfd0560ee6b5ca0d4408180964987c3978
doNotRelease: false
