url: https://github.com/rancher/ob-team-charts.git
subdirectory: charts/rancher-monitoring/69.8.2-rancher.27
commit: 362ad30ac0791062f7957c586dc0c00147af395d
version: 106.1.5-rc.1
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/ob-team-charts.git
      subdirectory: charts/rancher-monitoring-crd/69.8.2-rancher.27
      commit: 362ad30ac0791062f7957c586dc0c00147af395d
doNotRelease: false
