url: https://github.com/rancher/ob-team-charts.git
subdirectory: charts/rancher-monitoring/69.8.2-rancher.29
commit: d0b443333fd4c2d3a214d9df8d5de0281c36977b
version: 107.2.3-rc.1
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/ob-team-charts.git
      subdirectory: charts/rancher-monitoring-crd/69.8.2-rancher.29
      commit: d0b443333fd4c2d3a214d9df8d5de0281c36977b
doNotRelease: false
