apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system-legacy
spec:
  components:
    base:
      enabled: {{ .Values.base.enabled }}
    egressGateways:
    - enabled: {{ .Values.egressGateways.enabled }}
      name: istio-egressgateway
      k8s:
      {{- if .Values.egressGateways.hpaSpec }}
        hpaSpec: {{ toYaml .Values.egressGateways.hpaSpec | nindent 12 }}
      {{- end }}
      {{- if .Values.egressGateways.podDisruptionBudget }}
        podDisruptionBudget: {{ toYaml .Values.egressGateways.podDisruptionBudget | nindent 12 }}
      {{- end }}
        nodeSelector: {{ include "linux-node-selector" . | nindent 12 }}
{{- if .Values.nodeSelector }}
{{- toYaml .Values.nodeSelector | nindent 12 }}
{{- end }}
        tolerations: {{ include "linux-node-tolerations" . | nindent 12 }}
{{- if .Values.tolerations }}
{{- toYaml .Values.tolerations | nindent 12 }}
{{- end }}
    ingressGateways:
    - enabled: {{ .Values.ingressGateways.enabled }}
      name: istio-ingressgateway
      k8s:
      {{- if .Values.ingressGateways.hpaSpec }}
        hpaSpec: {{ toYaml .Values.ingressGateways.hpaSpec | nindent 12 }}
      {{- end }}
      {{- if .Values.ingressGateways.podDisruptionBudget }}
        podDisruptionBudget: {{ toYaml .Values.ingressGateways.podDisruptionBudget | nindent 12 }}
      {{- end }}
        nodeSelector: {{ include "linux-node-selector" . | nindent 12 }}
{{- if .Values.nodeSelector }}
{{- toYaml .Values.nodeSelector | nindent 12 }}
{{- end }}
        tolerations: {{ include "linux-node-tolerations" . | nindent 12 }}
{{- if .Values.tolerations }}
{{- toYaml .Values.tolerations | nindent 12 }}
{{- end }}
    istiodRemote:
      enabled: {{ .Values.istiodRemote.enabled }}
    pilot:
      enabled: {{ .Values.legacy.pilot.enabled }}
      k8s:
      {{- if .Values.legacy.pilot.hpaSpec }}
        hpaSpec: {{ toYaml .Values.legacy.pilot.hpaSpec | nindent 12 }}
      {{- end }}
      {{- if .Values.pilot.podDisruptionBudget }}
        podDisruptionBudget: {{ toYaml .Values.pilot.legacy.podDisruptionBudget | nindent 12 }}
      {{- end }}
        nodeSelector: {{ include "linux-node-selector" . | nindent 12 }}
{{- if .Values.nodeSelector }}
{{- toYaml .Values.nodeSelector | nindent 12 }}
{{- end }}
        tolerations: {{ include "linux-node-tolerations" . | nindent 12 }}
{{- if .Values.tolerations }}
{{- toYaml .Values.tolerations | nindent 12 }}
{{- end }}
  hub: {{ .Values.systemDefaultRegistry | default "docker.io" }}
  profile: default
  tag: {{ .Values.legacy.tag }}
  revision: legacy
  meshConfig:
    discoverySelectors:
      - matchLabels:
          istio: legacy
    defaultConfig:
      proxyMetadata:
      {{- if .Values.dns.enabled }}
        ISTIO_META_DNS_CAPTURE: "true"
      {{- end }}
  values:
    gateways:
      istio-egressgateway:
        name: istio-egressgateway
        type: {{ .Values.egressGateways.type }}
      istio-ingressgateway:
        name: istio-ingressgateway
        type: {{ .Values.ingressGateways.type }}
    global:
      istioNamespace: istio-system-legacy
      proxy:
        image: {{ template "system_default_registry" . }}{{ .Values.legacy.proxy.repository }}:{{ .Values.legacy.proxy.tag }}
      proxy_init:
        image: {{ template "system_default_registry" . }}{{ .Values.legacy.proxy_init.repository }}:{{ .Values.legacy.proxy_init.tag }}
      {{- if .Values.legacy.defaultPodDisruptionBudget.enabled }}
      defaultPodDisruptionBudget:
        enabled: {{ .Values.legacy.defaultPodDisruptionBudget.enabled }}
      {{- end }}
    {{- if .Values.legacy.pilot.enabled }}
    pilot:
      env:
        ENABLE_ENHANCED_RESOURCE_SCOPING: true
      image: {{ template "system_default_registry" . }}{{ .Values.legacy.pilot.repository }}:{{ .Values.legacy.pilot.tag }}
    {{- end }}
    telemetry:
      enabled: {{ .Values.telemetry.enabled }}
      v2:
        enabled: {{ .Values.telemetry.v2.enabled }}
    {{- if .Values.cni.enabled }}
    cni:
      image: {{ template "system_default_registry" . }}{{ .Values.cni.repository }}:{{ .Values.cni.tag }}
      excludeNamespaces:
      {{- toYaml .Values.cni.excludeNamespaces | nindent 8 }}
      logLevel: {{ .Values.cni.logLevel }}
    {{- end }}
