url: https://github.com/rancher/ob-team-charts.git
subdirectory: charts/rancher-monitoring/77.9.1-rancher.9
commit: f16f45109401bab80fe44339b0ecec06927a7007
version: 108.0.0-rc.4
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/ob-team-charts.git
      subdirectory: charts/rancher-monitoring-crd/77.9.1-rancher.9
      commit: f16f45109401bab80fe44339b0ecec06927a7007
doNotRelease: false
