kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: istio-installer
subjects:
- kind: ServiceAccount
  name: istio-installer
  namespace: {{ template "istio.namespace" . }}
- kind: ServiceAccount
  name: istio-installer-legacy
  namespace: {{ template "istio.namespace" . }}-legacy
roleRef:
  kind: ClusterRole
  name: istio-installer
  apiGroup: rbac.authorization.k8s.io
